"""create users table

Revision ID: c5ba807f4e60
Revises: 33d1fa5c5e1a
Create Date: 2026-05-15 14:46:56.691801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5ba807f4e60'
down_revision: Union[str, Sequence[str], None] = '33d1fa5c5e1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_schema',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_schema_email'), 'users_schema', ['email'], unique=True)
    op.create_index(op.f('ix_users_schema_id'), 'users_schema', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_schema_id'), table_name='users_schema')
    op.drop_index(op.f('ix_users_schema_email'), table_name='users_schema')
    op.drop_table('users_schema')
    # ### end Alembic commands ###
